In [1]:
import pandas as pd

In [22]:
data = {
    'Name' : ["Monika", "Ragini " ,"Ragini","Daksh" ,"Sneha"],
    "Age"  : [18,19,46,25,45],
    "Score" : [90,45,60,89,95],
    "Height" : [4,5,9,6,7]
}

df = pd.DataFrame(data)

In [23]:
df

      Name  Age  Score  Height
0   Monika   18     90       4
1  Ragini    19     45       5
2   Ragini   46     60       9
3    Daksh   25     89       6
4    Sneha   45     95       7

In [4]:
df.sort_values(by = 'Score',ascending=False)

      Name  Age  Score  Height
4    Sneha   45     95       7
0   Monika   18     90       4
3    Daksh   25     89       6
2   Shivam   46     60       9
1  Shweta    19     45       5

In [13]:
print("MEAN")
print(df.mean(numeric_only=True))
print("MODE")
print(df.mode(numeric_only=True))
print("MEDIAN")
print(df.median(numeric_only=True))
print("STD")
print(df.std(numeric_only=True))

MEAN
Age       30.6
Score     75.8
Height     6.2
dtype: float64
MODE
   Age  Score  Height
0   18     45       4
1   19     60       5
2   25     89       6
3   45     90       7
4   46     95       9
MEDIAN
Age       25.0
Score     89.0
Height     6.0
dtype: float64
STD
Age       13.867228
Score     22.038602
Height     1.923538
dtype: float64

In [24]:
df.value_counts('Name')

Name
Daksh      1
Monika     1
Ragini     1
Ragini     1
Sneha      1
Name: count, dtype: int64

In [26]:
df['Name'] = df['Name'].str.strip()

In [28]:
df.value_counts('Name',normalize=True)

Name
Ragini    0.4
Daksh     0.2
Monika    0.2
Sneha     0.2
Name: proportion, dtype: float64

In [29]:
df.corr(numeric_only=True)

             Age     Score    Height
Age     1.000000  0.112560  0.912869
Score   0.112560  1.000000 -0.152151
Height  0.912869 -0.152151  1.000000

In [30]:
df.cov(numeric_only=True)

           Age   Score  Height
Age     192.30   34.40   24.35
Score    34.40  485.70   -6.45
Height   24.35   -6.45    3.70