In [1]:
import pandas as pd

In [2]:
data = {
    "Name" : ["Monika" ,"Kirti" , "Shikha", "Shweta","Teena"],
    "Age"  : [18,41,58,99,100],
    "City"  : ["Delhi" , "Jaipur" , "Mumbai" , "Goa" , "Gujarat"],
    "Score"  : [90,80,56,41,23]
}
df = pd.DataFrame(data)
df

     Name  Age     City  Score
0  Monika   18    Delhi     90
1   Kirti   41   Jaipur     80
2  Shikha   58   Mumbai     56
3  Shweta   99      Goa     41
4   Teena  100  Gujarat     23

In [3]:
df[df['Age']>25]

     Name  Age     City  Score
1   Kirti   41   Jaipur     80
2  Shikha   58   Mumbai     56
3  Shweta   99      Goa     41
4   Teena  100  Gujarat     23

In [4]:
df

     Name  Age     City  Score
0  Monika   18    Delhi     90
1   Kirti   41   Jaipur     80
2  Shikha   58   Mumbai     56
3  Shweta   99      Goa     41
4   Teena  100  Gujarat     23

In [5]:
df[(df['City'] == "Delhi")|(df['City'] == "Mumbai")]

     Name  Age    City  Score
0  Monika   18   Delhi     90
2  Shikha   58  Mumbai     56

In [7]:
# df.query("Score >=85" & Age < 35)

In [15]:
print(df['Name'].str.upper())
df['Name'].str.lower()

0    MONIKA
1     KIRTI
2    SHIKHA
3    SHWETA
4     TEENA
Name: Name, dtype: object

0    monika
1     kirti
2    shikha
3    shweta
4     teena
Name: Name, dtype: object

In [14]:
df['City'].str.replace("Delhi" , "New Delhi")

0    New Delhi
1       Jaipur
2       Mumbai
3          Goa
4      Gujarat
Name: City, dtype: object