In [1]:
import pandas as pd

In [2]:
data = {
    "Name" : ["Monika","Shweta","Shivam","Daksh"] ,
     "Age" :  [18 , 18 , 19 , 20],
     "Courses" : ["Data Science" , "Data Analysis" , "Web Development" , "Ethical Hacking"], 
     "Fee_stucture" : [8000 , 5000 , 6000 , 10000], 
    "Compeletion_rate" : [50.00 , 40.00 , 40.00 , 60.00]
}

df = pd.DataFrame(data)
df

     Name  Age          Courses  Fee_stucture  Compeletion_rate
0  Monika   18     Data Science          8000              50.0
1  Shweta   18    Data Analysis          5000              40.0
2  Shivam   19  Web Development          6000              40.0
3   Daksh   20  Ethical Hacking         10000              60.0

In [3]:
df.head(3)

     Name  Age          Courses  Fee_stucture  Compeletion_rate
0  Monika   18     Data Science          8000              50.0
1  Shweta   18    Data Analysis          5000              40.0
2  Shivam   19  Web Development          6000              40.0

In [4]:
df.tail(2)

     Name  Age          Courses  Fee_stucture  Compeletion_rate
2  Shivam   19  Web Development          6000              40.0
3   Daksh   20  Ethical Hacking         10000              60.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              4 non-null      object
 1   Age               4 non-null      int64
 2   Courses           4 non-null      object
 3   Fee_stucture      4 non-null      int64
 4   Compeletion_rate  4 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 292.0+ bytes

In [6]:
df[["Courses" , "Compeletion_rate"]]

           Courses  Compeletion_rate
0     Data Science              50.0
1    Data Analysis              40.0
2  Web Development              40.0
3  Ethical Hacking              60.0

In [7]:
df.rename(columns={"Compeletion_rate" : "Complete"})

     Name  Age          Courses  Fee_stucture  Complete
0  Monika   18     Data Science          8000      50.0
1  Shweta   18    Data Analysis          5000      40.0
2  Shivam   19  Web Development          6000      40.0
3   Daksh   20  Ethical Hacking         10000      60.0

In [8]:
df.set_index("Name",inplace=False)

        Age          Courses  Fee_stucture  Compeletion_rate
Name
Monika   18     Data Science          8000              50.0
Shweta   18    Data Analysis          5000              40.0
Shivam   19  Web Development          6000              40.0
Daksh    20  Ethical Hacking         10000              60.0

In [9]:
df.reset_index(inplace= False)
df

     Name  Age          Courses  Fee_stucture  Compeletion_rate
0  Monika   18     Data Science          8000              50.0
1  Shweta   18    Data Analysis          5000              40.0
2  Shivam   19  Web Development          6000              40.0
3   Daksh   20  Ethical Hacking         10000              60.0

In [23]:
import numpy as np
arr = df.values
print(arr)
df.shape
df.dtypes
df.columns

[['Monika' 18 'Data Science' 8000 50.0]
 ['Shweta' 18 'Data Analysis' 5000 40.0]
 ['Shivam' 19 'Web Development' 6000 40.0]
 ['Daksh' 20 'Ethical Hacking' 10000 60.0]]

Index(['Name', 'Age', 'Courses', 'Fee_stucture', 'Compeletion_rate'], dtype='object')