In [1]:
import pandas as pd

In [3]:
data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR", "Finance", "IT"],
    "Employee": ["Monika", "Rahul", "Sneha", "Daksh", "Ragini", "Amit", "Priya", "Vikas", "Neha", "Rohit"],
    "Salary": [45000, 72000, 60000, 85000, 48000, 55000, 90000, 42000, 67000, 78000],
    "Age": [25, 28, 32, 24, 30, 35, 27, 40, 29, 26],
    "City": ["Delhi", "Mumbai", "Bangalore", "Delhi", "Hyderabad", "Mumbai", "Pune", "Delhi", "Bangalore", "Mumbai"]
}

df = pd.DataFrame(data)

In [4]:
df

  Department Employee  Salary  Age       City
0         HR   Monika   45000   25      Delhi
1         IT    Rahul   72000   28     Mumbai
2    Finance    Sneha   60000   32  Bangalore
3         IT    Daksh   85000   24      Delhi
4         HR   Ragini   48000   30  Hyderabad
5    Finance     Amit   55000   35     Mumbai
6         IT    Priya   90000   27       Pune
7         HR    Vikas   42000   40      Delhi
8    Finance     Neha   67000   29  Bangalore
9         IT    Rohit   78000   26     Mumbai

In [7]:
print(df.groupby('Department')['Salary'].mean())
print(df.groupby('Department')['Age'].max())

Department
Finance    60666.666667
HR         45000.000000
IT         81250.000000
Name: Salary, dtype: float64
Department
Finance    35
HR         40
IT         28
Name: Age, dtype: int64

In [9]:
df.groupby('Department').agg({
    "Salary" : ['mean','min','max'],
    "Age"  : ['max']
})

                  Salary               Age
                    mean    min    max max
Department
Finance     60666.666667  55000  67000  35
HR          45000.000000  42000  48000  40
IT          81250.000000  72000  90000  28

In [13]:
pivot = df.pivot_table(values=['Salary'],index='City',columns='Department',aggfunc='mean')
pivot

             Salary
Department  Finance       HR       IT
City
Bangalore   63500.0      NaN      NaN
Delhi           NaN  43500.0  85000.0
Hyderabad       NaN  48000.0      NaN
Mumbai      55000.0      NaN  75000.0
Pune            NaN      NaN  90000.0

In [18]:
pivot['Salary'] =pivot['Salary'].fillna(pivot['Salary'].mean())
pivot

             Salary
Department  Finance       HR            IT
City
Bangalore   63500.0  45750.0  83333.333333
Delhi       59250.0  43500.0  85000.000000
Hyderabad   59250.0  48000.0  83333.333333
Mumbai      55000.0  45750.0  75000.000000
Pune        59250.0  45750.0  90000.000000

In [19]:
df

  Department Employee  Salary  Age       City
0         HR   Monika   45000   25      Delhi
1         IT    Rahul   72000   28     Mumbai
2    Finance    Sneha   60000   32  Bangalore
3         IT    Daksh   85000   24      Delhi
4         HR   Ragini   48000   30  Hyderabad
5    Finance     Amit   55000   35     Mumbai
6         IT    Priya   90000   27       Pune
7         HR    Vikas   42000   40      Delhi
8    Finance     Neha   67000   29  Bangalore
9         IT    Rohit   78000   26     Mumbai

In [25]:
pd.crosstab(df['Department'],df['City'],normalize=True)

City        Bangalore  Delhi  Hyderabad  Mumbai  Pune
Department
Finance           0.2    0.0        0.0     0.1   0.0
HR                0.0    0.2        0.1     0.0   0.0
IT                0.0    0.1        0.0     0.2   0.1