In [1]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

**checkout the info of your dataframe**

In [2]:
print(f"The total column of your data : {len(df.columns)}")
print(f"The total rows of your data : {len(df)}")
print(f"The total info of the dataframe is : {df.info}")


print(f"Total null values in the data is : {df.isna().sum()}")

The total column of your data : 5
The total rows of your data : 6
The total info of the dataframe is : <bound method DataFrame.info of      Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z>
Total null values in the data is : Name     1
Age      1
City     0
Score    1
Extra    0
dtype: int64

**copy the orginal data then make changes in the copied**

In [3]:
copied = df.copy()
copied

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

**fill the null values**

nulll values in the column name if filled with unknown

In [4]:
copied['Name'] = copied['Name'].fillna("Unknown")
copied

      Name   Age       City  Score Extra
0    Alice    25      Delhi   85.0     x
1      Bob    30     Mumbai    NaN     y
2   Chrlie  None        Pun   78.0     z
3    David    40  Bangalore   88.0     x
4    Alice    25      Delhi   85.0     y
5  Unknown    30     Mumbai   91.0     z

filling the null values in the column age with mean of whole column

In [5]:
copied['Age'].dtypes

dtype('O')

In [6]:
copied['Age'] = copied['Age'].fillna(0)
print(copied)
copied['Age'].dtype

      Name Age       City  Score Extra
0    Alice  25      Delhi   85.0     x
1      Bob  30     Mumbai    NaN     y
2   Chrlie   0        Pun   78.0     z
3    David  40  Bangalore   88.0     x
4    Alice  25      Delhi   85.0     y
5  Unknown  30     Mumbai   91.0     z

dtype('O')

In [7]:
copied['Age'] = copied['Age'].astype(int)
copied['Age'].dtype

dtype('int64')

In [8]:
copied['Age'] = copied['Age'].replace({0:copied['Age'].mean()})
copied

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    NaN     y
2   Chrlie   25        Pun   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

removing the null values from the column score

In [9]:
copied['Score'].dtype

dtype('float64')

In [10]:
copied['Score'] = copied['Score'].fillna(copied['Score'].mean())
copied

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai   85.4     y
2   Chrlie   25        Pun   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [11]:
copied

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai   85.4     y
2   Chrlie   25        Pun   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [18]:
copied.drop('Extra',axis=1,inplace=True)
copied

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2   Chrlie   25        Pun   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5  Unknown   30     Mumbai   91.0

In [22]:
copied['City'] = copied['City'].replace({"Pun":"Pune"})
copied

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2   Chrlie   25       Pune   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5  Unknown   30     Mumbai   91.0

In [23]:
copied.info

<bound method DataFrame.info of       Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2   Chrlie   25       Pune   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5  Unknown   30     Mumbai   91.0>