In [1]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [2]:
c = df.copy()
c

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [3]:
c.isnull().sum()
c['Name'] = c['Name'].fillna("Unknown")
c

      Name   Age       City  Score Extra
0    Alice    25      Delhi   85.0     x
1      Bob    30     Mumbai    NaN     y
2   Chrlie  None        Pun   78.0     z
3    David    40  Bangalore   88.0     x
4    Alice    25      Delhi   85.0     y
5  Unknown    30     Mumbai   91.0     z

In [6]:
c['Age'] = c['Age'].astype(int)
print(c.dtypes)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'